## **Assignment 2 Group 63**
**Student Name:** Huzaifa Nissare-Houssen   
 **Student Number:** 300172186  
 **Student Name:** Fahmi Sajid Ahmed   
 **Student Number:** 300250180

### **Dataset Description: Netflix Movies and TV Shows**

---

#### **1. General Information**

 **Dataset Name:** Netflix Movies and TV Shows
   **Author:** Shivam Bansal   
   **Source:** https://www.kaggle.com/datasets/shivamb/netflix-shows  
   **Purpose:** This dataset was created to provide a comprehensive listing of all the movies and TV shows available on Netflix as of 2021. It is a real-world dataset intended for exploratory data analysis (EDA), trend tracking in the entertainment industry, and building recommendation engines. Researchers use it to compare content distribution across different countries and genres.

---

#### **2. Shape**

 **Rows:** 8,807  
 **Columns:** 12

---

#### **3. Features & Descriptions**

| Feature | Description | Type |
| --- | --- | --- |
| **`show_id`** | A unique identifier assigned to each movie or TV show. | **Categorical (ID)** |
| **`type`** | Identifies if the entry is a 'Movie' or a 'TV Show'. | **Categorical** |
| **`title`** | The official name of the content. | **Categorical (Text)** |
| **`director`** | The director(s) of the movie or show. (Contains many null values). | **Categorical** |
| **`cast`** | The primary actors and actresses featured in the title. | **Categorical** |
| **`country`** | The country or countries involved in the production of the content. | **Categorical** |
| **`date_added`** | The date the title was officially added to the Netflix library. | **Categorical (Date)** |
| **`release_year`** | The actual year the movie or show was first released. | **Numerical** |
| **`rating`** | The age-suitability rating (e.g., TV-MA, PG-13, R). | **Categorical** |
| **`duration`** | The length in minutes (Movies) or number of seasons (TV Shows). | **Numerical/Mixed** |
| **`listed_in`** | The genres assigned to the content (e.g., Horror, Documentaries). | **Categorical** |
| **`description`** | A short summary of the plot or premise. | **Categorical (Text)** |

In [1]:
import pandas as pd
import numpy as np
from IPython.display import display, HTML
import random
import string

url = 'https://raw.githubusercontent.com/Fahmi-IT/CSI4142_A2/refs/heads/main/data/netflix_titles.csv'
clean_data = pd.read_csv(url)

clean_data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:


def inject_numbers(df, column, decimal_percentage, min_val, max_val, type='int'):

    df_corrupted = df.copy()
    
    # 2. Calculate the number of rows to change
    n_rows = len(df_corrupted)
    n_to_replace = int(n_rows * decimal_percentage)
    
    if n_to_replace > 0:
        indices_to_replace = np.random.choice(df_corrupted.index, size=n_to_replace, replace=False)
        
        
        random_values = np.random.randint(min_val, max_val + 1, size=n_to_replace)
        if type == 'float':
            random_values = np.random.uniform(min_val, max_val + 1, size=n_to_replace)
        
        
        df_corrupted.loc[indices_to_replace, column] = random_values
        
    return df_corrupted




def add_numeric_sort_key(df, source_column):

    df_result = df.copy()
    cleaned_series = df_result[source_column].astype(str).str.replace(r'[^0-9]', '', regex=True)
    cleaned_series = cleaned_series.replace('', pd.NA)
    df_result['sort_key'] = pd.to_numeric(cleaned_series, errors='coerce').astype('Int64')

    return df_result

def compare_heads(df1, df2, label1="Original", label2="Modified"):
    # This creates a side-by-side view using basic HTML/CSS
    html_str = f"""
    <div style="display: flex; gap: 50px;">
        <div>
            <h3>{label1}</h3>
            {df1.head(3).to_html()}
        </div>
        <div>
            <h3>{label2}</h3>
            {df2.head(3).to_html()}
        </div>
    </div>
    """
    display(HTML(html_str))

def get_column_differences(df1, df2, join_col, compare_col):
    """
    Joins two dataframes and returns a list of IDs where 
    the compare_col values are different.
    """
    # 1. Merge the dataframes
    merged = pd.merge(df1, df2, on=join_col, suffixes=('_df1', '_df2'))
    
    # 2. Identify the differences
    # Note: Use .ne() or != for comparison
    diff_mask = merged[f'{compare_col}_df1'] != merged[f'{compare_col}_df2']
    
    # 3. Extract the join_col (show_id) for those rows
    affected_ids = merged.loc[diff_mask, join_col].unique().tolist()
    
    return affected_ids

def generate_report(clean_data, dirty_data, column):
    potential_to_remove = ['description', 'cast', 'date_added', 'listed_in', 'sort_key']
    
    if column in potential_to_remove:
        potential_to_remove.remove(column)
    
    sorted_clean = add_numeric_sort_key(clean_data, 'show_id').sort_values(by='sort_key')
    sorted_dirty = add_numeric_sort_key(dirty_data, 'show_id').sort_values(by='sort_key')
    
    diff = get_column_differences(sorted_clean, sorted_dirty, 'show_id', column)
    sorted_clean = sorted_clean[sorted_clean['show_id'].isin(diff)].copy()
    sorted_dirty = sorted_dirty[sorted_dirty['show_id'].isin(diff)].copy()
    
    
    compare_heads(
        sorted_clean.drop(columns=potential_to_remove, errors='ignore'), 
        sorted_dirty.drop(columns=potential_to_remove, errors='ignore'),
        label1="Original",
        label2="Changed"
    )

### Data Type Validatity Checker

This test verfies that the data type of the enteries is of the expected type

In [100]:


def inject_type_errors(df, column, decimal_percentage=0.1, error_type='float'):
    df_result = df.copy()
    

    df_result[column] = df_result[column].astype(object)
    
    n_rows = len(df_result)
    n_to_replace = int(n_rows * decimal_percentage)
    
    if n_to_replace > 0:
        target_indices = np.random.choice(df_result.index, size=n_to_replace, replace=False)
        
        if error_type == 'string':
            bad_data = "INVALID_TYPE"
        elif error_type == 'float':
            bad_data = 999.99  
        else:
            bad_data = None
            
        df_result.loc[target_indices, column] = bad_data
        
    return df_result


dirty_data = inject_type_errors(clean_data, 'release_year', 0.1, 'float')

In [101]:
def check_data_type(df, column, expected_type):
    errors = df[df[column].apply(lambda x: not isinstance(x, expected_type))]
    return errors

errors = check_data_type(dirty_data, 'release_year', int)

In [13]:
compare_heads(clean_data, errors, 'Original', 'Changed')

### Range Validity Checker

This test verifies if the data is in a valid range

In [73]:
def inject_numbers(df, column, decimal_percentage, min_val, max_val):

    df_corrupted = df.copy()
    
    # 2. Calculate the number of rows to change
    n_rows = len(df_corrupted)
    n_to_replace = int(n_rows * decimal_percentage)
    
    if n_to_replace > 0:
        indices_to_replace = np.random.choice(df_corrupted.index, size=n_to_replace, replace=False)
        
        random_values = np.random.randint(min_val, max_val + 1, size=n_to_replace)
        
        df_corrupted.loc[indices_to_replace, column] = random_values
        
    return df_corrupted

dirty_data = inject_numbers(clean_data,'release_year',0.1, 1765, 1890)

In [74]:
def check_range(df, column, min_val, max_val):
    return df[(df[column] < min_val) | (df[column] > max_val)]

errors = check_range(dirty_data, 'release_year', 1900, 2026)

In [75]:
#final report with example
generate_report(clean_data, errors, 'release_year')

[32, 36, 38, 42, 45, 53, 54, 58, 71, 78, 104, 114, 123, 144, 148, 157, 167, 177, 189, 203, 210, 225, 228, 231, 243, 270, 271, 301, 307, 316, 327, 328, 330, 346, 350, 353, 402, 411, 440, 450, 451, 458, 459, 463, 473, 479, 499, 500, 504, 509, 510, 513, 519, 539, 540, 541, 544, 560, 581, 583, 584, 590, 599, 605, 609, 635, 642, 650, 662, 670, 681, 696, 715, 718, 722, 728, 730, 752, 754, 776, 783, 785, 787, 813, 814, 815, 823, 826, 843, 876, 883, 886, 898, 917, 952, 955, 965, 969, 970, 974, 1004, 1008, 1039, 1045, 1046, 1053, 1076, 1090, 1103, 1108, 1109, 1118, 1120, 1137, 1138, 1140, 1153, 1155, 1160, 1162, 1183, 1184, 1188, 1201, 1206, 1207, 1218, 1222, 1229, 1266, 1275, 1289, 1303, 1315, 1328, 1339, 1346, 1348, 1363, 1376, 1384, 1396, 1401, 1422, 1433, 1464, 1465, 1471, 1488, 1503, 1516, 1526, 1528, 1542, 1544, 1550, 1552, 1558, 1571, 1574, 1576, 1577, 1580, 1585, 1594, 1601, 1602, 1621, 1629, 1631, 1648, 1657, 1675, 1678, 1687, 1701, 1710, 1711, 1715, 1716, 1720, 1721, 1746, 1747, 1748, 1759, 1761, 1767, 1772, 1790, 1804, 1807, 1808, 1823, 1842, 1851, 1867, 1873, 1901, 1903, 1910, 1915, 1920, 1927, 1931, 1933, 1954, 1957, 1973, 1974, 1975, 1985, 1999, 2005, 2006, 2007, 2009, 2058, 2062, 2067, 2072, 2092, 2106, 2110, 2124, 2125, 2137, 2146, 2155, 2166, 2167, 2169, 2174, 2223, 2254, 2284, 2288, 2302, 2303, 2306, 2309, 2316, 2325, 2347, 2351, 2358, 2359, 2367, 2374, 2383, 2386, 2408, 2431, 2438, 2449, 2486, 2498, 2513, 2523, 2528, 2532, 2535, 2536, 2544, 2559, 2568, 2591, 2611, 2638, 2655, 2663, 2666, 2669, 2676, 2710, 2712, 2724, 2735, 2746, 2766, 2789, 2831, 2844, 2845, 2869, 2876, 2899, 2906, 2919, 2938, 2965, 2972, 2973, 2978, 2987, 3003, 3004, 3013, 3016, 3030, 3032, 3033, 3043, 3044, 3061, 3087, 3096, 3097, 3119, 3128, 3131, 3139, 3152, 3153, 3161, 3167, 3182, 3200, 3203, 3234, 3253, 3267, 3279, 3286, 3290, 3317, 3319, 3324, 3326, 3327, 3328, 3330, 3345, 3368, 3371, 3384, 3385, 3406, 3407, 3408, 3416, 3434, 3447, 3463, 3471, 3483, 3492, 3511, 3513, 3521, 3524, 3541, 3551, 3579, 3587, 3589, 3595, 3621, 3633, 3660, 3663, 3675, 3685, 3687, 3761, 3779, 3805, 3826, 3828, 3830, 3836, 3840, 3846, 3847, 3855, 3859, 3877, 3878, 3883, 3888, 3889, 3891, 3900, 3902, 3909, 3914, 3920, 3923, 3952, 3980, 3981, 3984, 3996, 4014, 4024, 4030, 4032, 4034, 4049, 4065, 4075, 4083, 4085, 4097, 4113, 4120, 4157, 4161, 4164, 4169, 4182, 4190, 4194, 4195, 4202, 4215, 4219, 4222, 4229, 4260, 4295, 4304, 4309, 4310, 4311, 4348, 4378, 4380, 4388, 4405, 4424, 4425, 4426, 4442, 4450, 4451, 4465, 4471, 4474, 4505, 4514, 4521, 4523, 4548, 4560, 4564, 4580, 4583, 4585, 4587, 4606, 4607, 4614, 4615, 4621, 4626, 4629, 4634, 4657, 4660, 4667, 4675, 4700, 4709, 4712, 4717, 4721, 4763, 4768, 4772, 4803, 4863, 4864, 4866, 4880, 4931, 4940, 4971, 4976, 4978, 5007, 5010, 5012, 5019, 5022, 5023, 5026, 5030, 5034, 5037, 5047, 5049, 5062, 5129, 5132, 5151, 5156, 5157, 5159, 5166, 5167, 5184, 5193, 5203, 5208, 5218, 5221, 5255, 5259, 5265, 5266, 5271, 5282, 5287, 5292, 5300, 5303, 5306, 5316, 5319, 5327, 5331, 5334, 5345, 5350, 5354, 5371, 5385, 5404, 5405, 5408, 5428, 5453, 5462, 5467, 5508, 5512, 5514, 5517, 5530, 5533, 5540, 5552, 5559, 5564, 5581, 5583, 5598, 5606, 5610, 5613, 5615, 5620, 5625, 5637, 5640, 5658, 5686, 5700, 5713, 5715, 5738, 5746, 5763, 5764, 5771, 5772, 5773, 5780, 5785, 5801, 5810, 5819, 5821, 5826, 5832, 5833, 5843, 5847, 5858, 5877, 5882, 5889, 5893, 5908, 5909, 5913, 5928, 5933, 5935, 5952, 5960, 5967, 5976, 5998, 6014, 6018, 6019, 6039, 6051, 6054, 6092, 6107, 6111, 6114, 6120, 6121, 6128, 6129, 6138, 6142, 6153, 6160, 6169, 6182, 6188, 6217, 6234, 6241, 6247, 6264, 6282, 6284, 6293, 6295, 6302, 6303, 6310, 6316, 6387, 6404, 6433, 6436, 6449, 6451, 6456, 6459, 6469, 6494, 6503, 6517, 6522, 6527, 6535, 6538, 6562, 6570, 6586, 6592, 6598, 6618, 6622, 6627, 6629, 6634, 6639, 6643, 6645, 6647, 6656, 6670, 6680, 6695, 6701, 6708, 6723, 6726, 6756, 6760, 6767, 6778, 6791, 6801, 6808, 6815, 6817, 6819, 6832, 6842, 6868, 6870, 6878, 6885, 6899, 6906, 6911, 6917, 6935, 6936, 6945, 6958, 6963, 6967, 6988, 6989, 6992, 7013, 7043, 7073, 7077, 7087, 7095, 7106, 7130, 7135, 7138, 7151, 7153, 7156, 7169, 7187, 7198, 7203, 7204, 7205, 7207, 7208, 7217, 7234, 7242, 7260, 7273, 7280, 7303, 7304, 7308, 7310, 7326, 7350, 7354, 7371, 7379, 7384, 7392, 7398, 7408, 7410, 7425, 7426, 7432, 7434, 7449, 7458, 7461, 7473, 7475, 7476, 7499, 7503, 7505, 7506, 7507, 7522, 7526, 7544, 7547, 7559, 7575, 7587, 7592, 7615, 7643, 7646, 7649, 7659, 7671, 7680, 7690, 7696, 7698, 7704, 7726, 7741, 7778, 7780, 7784, 7786, 7790, 7798, 7801, 7812, 7841, 7852, 7854, 7855, 7863, 7866, 7900, 7902, 7904, 7908, 7921, 7947, 7967, 7979, 8038, 8040, 8041, 8050, 8061, 8062, 8066, 8071, 8078, 8082, 8087, 8089, 8093, 8100, 8122, 8125, 8146, 8174, 8189, 8199, 8211, 8235, 8241, 8243, 8247, 8252, 8269, 8277, 8278, 8279, 8291, 8296, 8304, 8305, 8315, 8319, 8324, 8334, 8346, 8354, 8366, 8389, 8391, 8405, 8427, 8430, 8438, 8445, 8454, 8461, 8463, 8478, 8486, 8507, 8514, 8528, 8550, 8576, 8586, 8598, 8602, 8622, 8628, 8634, 8637, 8641, 8645, 8654, 8657, 8660, 8662, 8666, 8672, 8688, 8697, 8710, 8711, 8739, 8744, 8783, 8787, 8794, 8801, 8804, 8805]

### Format Validity Checker

This test verifies if data is in a valid format

In [93]:
def inject_string_errors(df, column, percentage, string_length=5):
    """
    Creates a copy of a dataframe and replaces a % of a column 
    with a random string (e.g., 'aZ3pQ').
    """
    df_corrupted = df.copy()
    
    n_rows = len(df_corrupted)
    n_to_replace = int(n_rows * (percentage / 100))
    
    if n_to_replace > 0:
        indices_to_replace = np.random.choice(df_corrupted.index, size=n_to_replace, replace=False)
        
        chars = string.ascii_letters + string.digits
        
        random_strings = [
            ''.join(random.choice(chars) for _ in range(string_length)) 
            for _ in range(n_to_replace)
        ]
        
        df_corrupted.loc[indices_to_replace, column] = random_strings
        
    return df_corrupted

dirty_data = inject_string_errors(clean_data, 'date_added', 0.1)

In [94]:
def check_format(df, column, regex_pattern):
    return df[~df[column].astype(str).str.contains(regex_pattern, na=True)]


valid_pattern = '^(January|February|March|April|May|June|July|August|September|October|November|December)\\s\\d{1,2},\\s\\d{4}$'

errors = check_format(dirty_data, 'date_added', valid_pattern).head()

/var/folders/3w/1_sy9lz53_d08dv59ywyyw700000gn/T/ipykernel_46683/2485409835.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  return df[~df[column].astype(str).str.contains(regex_pattern, na=True)]

In [95]:
#final report with example
generate_report(clean_data, errors, 'date_added')

[738, 4180, 4861, 5349, 5495]

### Consistency Validity Checker
 This test checks the consistency of a row

In [85]:

def invalidate_date_added(df, column='date_added', decimal_percentage=0.1):
  
    df_result = df.copy()
    

    n_rows = len(df_result)
    n_to_invalidate = int(n_rows * decimal_percentage)
    
    if n_to_invalidate > 0:
        target_indices = np.random.choice(df_result.index, size=n_to_invalidate, replace=False)
        
        
        subset = df_result.loc[target_indices, column].str.split(',', n=1, expand=True)
        
        if subset.shape[1] >= 2:
            numeric_part = pd.to_numeric(subset[1].str.strip(), errors='coerce')
            modified_number = (numeric_part - 100).astype(str)
            
       
            df_result.loc[target_indices, column] = subset[0] + ', ' + modified_number
            
    return df_result
dirty_data = invalidate_date_added(clean_data)

In [86]:
def year_consistency(df):
    df['date_added'] =  pd.to_numeric(df['date_added'].str.split(',', expand=True)[1], errors='coerce')
    mask = df['date_added'] < df['release_year']
    return df[mask]


errors = year_consistency(dirty_data)

In [87]:
#final report with example
generate_report(clean_data, errors, 'date_added')

[4, 27, 29, 37, 41, 64, 82, 88, 99, 103, 121, 123, 129, 161, 170, 177, 192, 215, 221, 230, 260, 264, 265, 266, 267, 270, 276, 322, 337, 372, 373, 376, 391, 401, 414, 421, 422, 430, 435, 455, 462, 470, 475, 479, 485, 491, 503, 511, 517, 520, 527, 531, 536, 560, 562, 571, 580, 591, 596, 599, 616, 649, 659, 671, 678, 679, 687, 698, 710, 711, 727, 728, 730, 739, 749, 755, 772, 778, 796, 827, 853, 866, 868, 874, 879, 896, 897, 921, 922, 923, 924, 960, 964, 965, 973, 979, 981, 985, 992, 1013, 1014, 1035, 1036, 1042, 1043, 1050, 1055, 1057, 1059, 1069, 1073, 1078, 1102, 1112, 1115, 1123, 1128, 1142, 1144, 1145, 1146, 1170, 1172, 1198, 1204, 1209, 1215, 1217, 1225, 1234, 1250, 1258, 1281, 1290, 1302, 1311, 1312, 1314, 1324, 1329, 1341, 1347, 1352, 1364, 1368, 1369, 1379, 1381, 1383, 1393, 1396, 1408, 1430, 1432, 1446, 1463, 1468, 1486, 1514, 1530, 1542, 1544, 1552, 1557, 1597, 1607, 1608, 1624, 1629, 1631, 1644, 1692, 1696, 1697, 1729, 1742, 1751, 1755, 1767, 1768, 1780, 1791, 1829, 1831, 1837, 1849, 1857, 1863, 1870, 1871, 1881, 1913, 1918, 1921, 1938, 1944, 1969, 1970, 1979, 1985, 1994, 1998, 2001, 2018, 2025, 2031, 2034, 2038, 2047, 2052, 2053, 2054, 2060, 2072, 2083, 2101, 2106, 2110, 2113, 2135, 2195, 2200, 2208, 2209, 2211, 2216, 2218, 2226, 2228, 2248, 2256, 2280, 2283, 2287, 2288, 2298, 2303, 2313, 2334, 2342, 2361, 2380, 2381, 2416, 2444, 2453, 2464, 2473, 2483, 2484, 2485, 2500, 2533, 2568, 2571, 2582, 2605, 2618, 2620, 2650, 2662, 2701, 2705, 2711, 2713, 2715, 2721, 2726, 2729, 2736, 2748, 2757, 2758, 2759, 2762, 2763, 2766, 2771, 2785, 2793, 2799, 2834, 2837, 2840, 2848, 2854, 2879, 2882, 2889, 2891, 2899, 2907, 2908, 2909, 2912, 2919, 2921, 2922, 2923, 2944, 2950, 2969, 2991, 3006, 3010, 3022, 3028, 3035, 3036, 3037, 3043, 3057, 3069, 3072, 3091, 3098, 3104, 3106, 3107, 3119, 3135, 3136, 3161, 3167, 3169, 3172, 3179, 3188, 3196, 3200, 3206, 3222, 3230, 3237, 3250, 3280, 3282, 3288, 3289, 3308, 3313, 3316, 3321, 3326, 3334, 3342, 3345, 3346, 3363, 3370, 3386, 3398, 3413, 3434, 3435, 3442, 3444, 3457, 3475, 3480, 3482, 3497, 3517, 3519, 3552, 3560, 3571, 3580, 3591, 3594, 3606, 3626, 3633, 3640, 3648, 3650, 3653, 3665, 3673, 3683, 3693, 3715, 3728, 3731, 3735, 3737, 3742, 3759, 3761, 3774, 3787, 3792, 3797, 3805, 3807, 3818, 3829, 3837, 3841, 3860, 3861, 3874, 3876, 3901, 3906, 3911, 3936, 3939, 3950, 3964, 3968, 3973, 3985, 3996, 4021, 4034, 4043, 4044, 4061, 4062, 4078, 4098, 4100, 4108, 4116, 4130, 4133, 4150, 4164, 4173, 4177, 4196, 4205, 4222, 4223, 4241, 4250, 4254, 4263, 4283, 4286, 4297, 4314, 4334, 4374, 4380, 4384, 4386, 4411, 4420, 4431, 4436, 4443, 4460, 4461, 4466, 4468, 4476, 4484, 4493, 4496, 4507, 4522, 4532, 4535, 4547, 4552, 4555, 4559, 4560, 4584, 4589, 4594, 4595, 4604, 4611, 4620, 4644, 4645, 4654, 4657, 4669, 4675, 4697, 4703, 4715, 4752, 4753, 4759, 4771, 4772, 4775, 4790, 4796, 4810, 4816, 4817, 4819, 4821, 4841, 4845, 4846, 4852, 4857, 4860, 4864, 4868, 4872, 4884, 4903, 4904, 4909, 4910, 4920, 4928, 4931, 4932, 4939, 4963, 4964, 4971, 4977, 5014, 5028, 5029, 5059, 5072, 5077, 5079, 5084, 5098, 5101, 5107, 5114, 5115, 5125, 5127, 5128, 5134, 5166, 5173, 5185, 5192, 5197, 5233, 5238, 5259, 5260, 5265, 5309, 5316, 5351, 5380, 5386, 5395, 5396, 5411, 5417, 5431, 5450, 5451, 5454, 5461, 5466, 5483, 5487, 5506, 5508, 5521, 5524, 5528, 5529, 5537, 5569, 5591, 5610, 5614, 5637, 5651, 5659, 5669, 5678, 5683, 5692, 5706, 5711, 5712, 5721, 5723, 5727, 5728, 5737, 5750, 5754, 5761, 5765, 5785, 5787, 5795, 5802, 5816, 5829, 5831, 5853, 5865, 5876, 5882, 5892, 5896, 5950, 5953, 5959, 5960, 5980, 5986, 5987, 6023, 6029, 6045, 6058, 6080, 6113, 6116, 6120, 6125, 6134, 6143, 6151, 6159, 6162, 6180, 6183, 6190, 6196, 6197, 6214, 6215, 6230, 6241, 6249, 6255, 6262, 6263, 6271, 6277, 6284, 6287, 6288, 6325, 6333, 6339, 6341, 6343, 6348, 6352, 6359, 6363, 6373, 6398, 6413, 6425, 6427, 6439, 6457, 6474, 6482, 6483, 6486, 6534, 6541, 6545, 6568, 6570, 6572, 6579, 6606, 6610, 6611, 6621, 6658, 6663, 6685, 6691, 6713, 6722, 6742, 6743, 6756, 6770, 6779, 6781, 6795, 6804, 6811, 6815, 6820, 6825, 6846, 6854, 6872, 6883, 6885, 6896, 6897, 6899, 6900, 6911, 6915, 6922, 6928, 6947, 6981, 6984, 6986, 7008, 7016, 7017, 7020, 7032, 7033, 7047, 7049, 7064, 7067, 7070, 7082, 7113, 7114, 7115, 7118, 7138, 7153, 7177, 7185, 7199, 7202, 7206, 7212, 7213, 7218, 7220, 7222, 7231, 7239, 7246, 7251, 7279, 7290, 7300, 7323, 7324, 7334, 7354, 7358, 7362, 7376, 7397, 7403, 7408, 7409, 7415, 7427, 7447, 7459, 7465, 7467, 7469, 7484, 7486, 7492, 7494, 7547, 7560, 7561, 7566, 7581, 7596, 7599, 7613, 7632, 7650, 7667, 7686, 7698, 7738, 7745, 7752, 7759, 7763, 7768, 7769, 7779, 7780, 7782, 7792, 7809, 7812, 7816, 7824, 7836, 7841, 7857, 7872, 7876, 7881, 7896, 7897, 7898, 7901, 7904, 7907, 7913, 7921, 7926, 7928, 7939, 7946, 7956, 7964, 7972, 7974, 7975, 7993, 7995, 7996, 8026, 8029, 8043, 8056, 8057, 8060, 8082, 8083, 8107, 8122, 8143, 8170, 8178, 8202, 8203, 8219, 8223, 8229, 8245, 8247, 8252, 8260, 8268, 8269, 8275, 8315, 8347, 8366, 8368, 8376, 8377, 8378, 8383, 8392, 8394, 8407, 8408, 8416, 8417, 8447, 8481, 8482, 8520, 8521, 8553, 8560, 8561, 8572, 8577, 8582, 8588, 8602, 8611, 8618, 8632, 8635, 8642, 8643, 8666, 8673, 8704, 8707, 8720, 8731, 8739, 8750, 8794]

### Uniqueness Validity Checker

This test validates that data is unique

In [16]:
def inject_ids(df, column, decimal_percentage, min_val, max_val):

    df_corrupted = df.copy()
    
    n_rows = len(df_corrupted)
    n_to_replace = int(n_rows * decimal_percentage)
    
    if n_to_replace > 0:
        indices_to_replace = np.random.choice(df_corrupted.index, size=n_to_replace, replace=False)
        
        random_values = np.random.randint(min_val, max_val + 1, size=n_to_replace)
        random_values_with_s = "s" + random_values.astype(str)
        
        df_corrupted.loc[indices_to_replace, column] = random_values_with_s
        
    return df_corrupted


dirty_data = inject_ids(clean_data, "show_id", 0.05, 1, 1000)

In [17]:
def check_uniqueness(df, column):
    return df[df.duplicated(subset=[column], keep=False)]


errors = check_uniqueness(dirty_data, 'show_id')
errors.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
12,s13,Movie,Je Suis Karl,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic","September 23, 2021",2021,TV-MA,127 min,"Dramas, International Movies",After most of her family is murdered in a terr...
14,s15,TV Show,Crime Stories: India Detectives,NaN,NaN,NaN,"September 22, 2021",2021,TV-MA,1 Season,"British TV Shows, Crime TV Shows, Docuseries",Cameras following Bengaluru police on the job ...

In [20]:

def get_common_rows(df1, df2, column):
    common_values = set(df2[column])
    common_df = df1[df1[column].isin(common_values)].copy()
    
    return common_df
    
    
common_values = get_common_rows(clean_data, errors, 'show_id')
compare_heads(
        common_values, 
       clean_data,
        label1="Original",
        label2="Changed"
    )

### Presecence Validity Checker

This test validates data that is not null or empty

In [53]:
#introduce error
def inject_presence_errors(df, column, decimal_percentage):

    df_corrupted = df.copy()
    
    n_rows = len(df_corrupted)
    n_to_nullify = int(n_rows * decimal_percentage)
    
    if n_to_nullify > 0:
        indices_to_replace = np.random.choice(df_corrupted.index, size=n_to_nullify, replace=False)
        
     
        df_corrupted.loc[indices_to_replace, column] = np.nan
        
    return df_corrupted

dirty_data = inject_presence_errors(clean_data, 'description', 0.1)

In [54]:
def check_presence(df, column):
    return df[df[column].isna() | (df[column].astype(str).str.strip() == "")]

errors = check_presence(dirty_data, 'description')

In [ ]:
#final report
generate_report(clean_data, errors, 'description')

### Length Validity Checker

This test tests if data is a certian length

In [81]:
#introduce error
dirty_data = inject_string_errors(clean_data, 'director', 0.1, 50)

In [82]:
def check_length(df, column, min_len, max_len):
    lengths = df[column].astype(str).str.len()
    return df[(lengths < min_len) | (lengths > max_len)]

errors = check_length(dirty_data,'director', 1, 30)

In [ ]:
generate_report(clean_data, errors, 'director')

### Look-up Validity Checker
This test verifies that all that elements are part of a valid set

In [ ]:
dirty_data = inject_string_errors(clean_data, 'rating', 0.1)

In [ ]:

def get_invalid_tv_ratings(df, column='rating'):

  
    valid_ratings = {
        'TV-Y', 'TV-Y7', 'TV-G', 'TV-PG', 'TV-14', 'TV-MA', 
        'G', 'PG', 'PG-13', 'R', 'NC-17', 'NR', 'UR'
    }
    

    check_series = df[column].astype(str).str.strip().str.upper()
    

    invalid_mask = ~check_series.isin(valid_ratings)
    
    return df[invalid_mask].copy()

errors = get_invalid_tv_ratings(dirty_data)

In [ ]:
generate_report(clean_data, errors, 'ratings')